### ISSUE TITLE
Upvote doesn't take into effect after list refreshed

### ISSUE THREAD

**Issue by toneywu** [voten-co/voten#100]
1\ submit a new post, with 1 point.
2\ another person up-vote the post, get 2 points on the screen.
3\ The up-voted person refresh the page, the up-voted icon shown as voted, but the counter back to 1 point.

**Comment by sullyfischer** [comment]
If that other person is voting via the same IP, then the behavior is expected as the new vote counts as cheating.

**Comment by toneywu** [comment]
we made a test with all different IPs
1. the 1st Person submitted a post with 1 point.
2. the 2nd Person up-voted to make it change from 1 point to 2 points.
3. the 3nd Person up-voted to make it change  from 2 points to 3 points.
4. the 4&5 person open the page at almost the same time, and there was 3 points shown on the screen, they up-voted and the count changed from 3 points to 2 points.

now all 5 person get a up-voted icon. but there are 2 points.

**Comment by sullyfischer** [comment]
If a user is seeing the voted icon but the points number is not updated (after refresh of course) it means that the anti-cheating function is returning true. It is an expected behavior.

**Comment by toneywu** [comment]
in my previous test , the points not only not updated **but also declined,** 

and what do you mean by same IP?
can people in the same intranet be treated as same IP?
Can users visit my hosted Voten sourcing from a same URL Hyper-Link be treated as same IP?

**Comment by toneywu** [comment]
ok. problem solved you're right. the ip captured in upvoted table is the docker's ip
