### ISSUE TITLE
(1/1) ConnectionException Aucune connexion n'a pu etre établie car l'ordinateur cible la expressement refusée. [tcp://127.0.0.1:6379]

### ISSUE THREAD

**Issue by tuayo77** [voten-co/voten#105]
hello 

a have clone the projet in local and donne all what you recommend to do 

bet a get that error 
**_(1/1) ConnectionException
Aucune connexion n�a pu �tre �tablie car l�ordinateur cible l�a express�ment refus�e. [tcp://127.0.0.1:6379]_**

please help 
ps:sorry for my wrong english

**Comment by sullyfischer** [comment]
I need to read the english version of that exception.

**Comment by sullyfischer** [comment]
I just translated it via Google Translator! You need to install and set Redis
