### ISSUE TITLE
Clickable Channel Links in comments and body

### ISSUE THREAD

**Issue by GeorgeNance** [voten-co/voten#117]
I think it would be very useful if `/c/test` or `#test` was parsed and embedded with a hyperlink to the channel.

Similar to how reddit handles `/r/`

[Example](https://www.reddit.com/r/AskReddit/comments/3t0p8e/what_is_your_favorite_subreddit_or_subreddits/)

See this:
https://www.reddit.com/r/changelog/comments/38ao4t/reddit_change_automatic_linking_of_rsubreddit_and/

**Comment by arswaw** [comment]
@GeorgeNance I like this idea. It shouldn't be too hard to write.

I will look through the code and see about contributing this feature.
