### ISSUE TITLE
When bio contains invalid UTF sequence, all pages refuse to load

### ISSUE THREAD

**Issue by adduc** [voten-co/voten#132]
Apologies if this is the incorrect place to report this, but after logging in via Google to https://voten.co/ , no pages load. None of the actions in the top bar work. This is what shows:

> ![screenshot from 2017-08-25 14-51-24](https://user-images.githubusercontent.com/44527/29730238-fbc12af6-89a4-11e7-8390-8357e84f1580.png)

Here's the error log on page load:

> ![screenshot from 2017-08-25 14-51-35](https://user-images.githubusercontent.com/44527/29730239-fbc2b470-89a4-11e7-8633-2cd4922e7968.png)

This is the relevant lines for the hexadecimal error:

> ![screenshot from 2017-08-25 14-51-47](https://user-images.githubusercontent.com/44527/29730237-fbbe8df0-89a4-11e7-9a76-06b7ddb37ec2.png)

**Comment by sullyfischer** [comment]
Hey man. My last push caused the issue. I hard-coded it on the production server. Will push the new code. Can you please check to see if it still exists? thanks

**Comment by adduc** [comment]
It appears to be working again.

Thanks!

**Comment by sullyfischer** [comment]
Thank YOU for the reporting!
