### ISSUE TITLE
Laravel's notifications data formats for broadcast driver and database driver are different.

### ISSUE THREAD

**Issue by lancepioch** [voten-co/voten#141]
From @sullyfischer's [comment](https://github.com/voten-co/voten/pull/21#issuecomment-309161372):

> Laravel's notifications data formats for broadcast driver and database driver are different. This causes an error when a notification is broadcasted. But after a refresh user can load the same notification and it works just fine (because this time it's being fetched from database).
>
> The production server however is working fine now and that's because back then I used to push /vendor files and in my local vendors files I've done this modification in Laravel core that takes care of it:
In BroadcastNotificationCreated.php:
>```php
>    /**
>     * Get the data that should be sent with the broadcasted event.
>     *
>     * @return array
>     */
>    public function broadcastWith()
>    {
>        return [
>        	'data' => $this->data,
>            'id' => $this->notification->id,
>            'type' => get_class($this->notification),
>            'created_at' => Carbon::now(),
>            'read_at' => null
>        ];
>
>        // return array_merge($this->data, [
>        //     'id' => $this->notification->id,
>        //     'type' => get_class($this->notification),
>        // ]);
>    }
>```
> Can you think of a "right way" for this?

**Comment by sullyfischer** [comment]
Maybe we should post this in Laravel forums as well?
