### ISSUE TITLE
Channel Issue

### ISSUE THREAD

**Issue by roottr** [voten-co/voten#168]
Hello After Fresh i tried to create a channel and it shows error message 

`{ "message": "Uncaught InvalidArgumentException: Type is not supported in /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:71\nStack trace:\n#0 /var/www/voten/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\\Http\\JsonResponse->setData(Array)\n#1 /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(27): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 500, Array)\n#2 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(435): Illuminate\\Http\\JsonResponse->__construct(Array, 500, Array, 192)\n#3 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(186): Illuminate\\Foundation\\Exceptions\\Handler->prepareJsonResponse(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#4 /var/www/voten/app/Exceptions/Handler.php(76): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))\n#5 /var/www/voten/vendor/laravel/fr", "exception": "Symfony\\Component\\Debug\\Exception\\FatalErrorException", "file": "/var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php", "line": 71, "trace": [] } `

My Log file 
`[2017-09-10 21:29:54] production.ERROR: Type is not supported {"userId":1,"email":"admin@admin.com","exception":"[object] (InvalidArgumentException(code: 0): Type is not supported at /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:71)
[stacktrace]
#0 /var/www/voten/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\\Http\\JsonResponse->setData(Array)
#1 /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(27): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 500, Array)
#2 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(435): Illuminate\\Http\\JsonResponse->__construct(Array, 500, Array, 192)
#3 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(186): Illuminate\\Foundation\\Exceptions\\Handler->prepareJsonResponse(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#4 /var/www/voten/app/Exceptions/Handler.php(76): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#5 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(83): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#6 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(55): Illuminate\\Routing\\Pipeline->handleException(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#7 /var/www/voten/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#9 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Router.php(571): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#10 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Router.php(549): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#11 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#12 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#13 /var/www/voten/app/Http/Middleware/Firewall.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/voten/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\Firewall->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/voten/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/voten/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/voten/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#24 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#25 /var/www/voten/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#26 {main}
"} 
[2017-09-10 21:29:54] production.ERROR: Type is not supported {"userId":1,"email":"admin@admin.com","exception":"[object] (InvalidArgumentException(code: 0): Type is not supported at /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:71)
[stacktrace]
#0 /var/www/voten/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\\Http\\JsonResponse->setData(Array)
#1 /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(27): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 500, Array)
#2 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(435): Illuminate\\Http\\JsonResponse->__construct(Array, 500, Array, 192)
#3 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(186): Illuminate\\Foundation\\Exceptions\\Handler->prepareJsonResponse(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#4 /var/www/voten/app/Exceptions/Handler.php(76): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#5 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(83): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#6 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): Illuminate\\Routing\\Pipeline->handleException(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#7 /var/www/voten/app/Http/Middleware/Firewall.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /var/www/voten/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\Firewall->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#9 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /var/www/voten/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/voten/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/voten/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#18 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#19 /var/www/voten/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#20 {main}
"} 
[2017-09-10 21:29:54] production.ERROR: Type is not supported {"userId":1,"email":"admin@admin.com","exception":"[object] (InvalidArgumentException(code: 0): Type is not supported at /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:71)
[stacktrace]
#0 /var/www/voten/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\\Http\\JsonResponse->setData(Array)
#1 /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(27): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 500, Array)
#2 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(435): Illuminate\\Http\\JsonResponse->__construct(Array, 500, Array, 192)
#3 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(186): Illuminate\\Foundation\\Exceptions\\Handler->prepareJsonResponse(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#4 /var/www/voten/app/Exceptions/Handler.php(76): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#5 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(83): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#6 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(55): Illuminate\\Routing\\Pipeline->handleException(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#7 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /var/www/voten/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#9 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /var/www/voten/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#12 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#13 /var/www/voten/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#15 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#16 /var/www/voten/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#17 {main}
"} 
[2017-09-10 21:29:54] production.ERROR: Type is not supported {"userId":1,"email":"admin@admin.com","exception":"[object] (InvalidArgumentException(code: 0): Type is not supported at /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:71)
[stacktrace]
#0 /var/www/voten/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\\Http\\JsonResponse->setData(Array)
#1 /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(27): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 500, Array)
#2 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(435): Illuminate\\Http\\JsonResponse->__construct(Array, 500, Array, 192)
#3 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(186): Illuminate\\Foundation\\Exceptions\\Handler->prepareJsonResponse(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#4 /var/www/voten/app/Exceptions/Handler.php(76): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#5 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(83): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#6 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(55): Illuminate\\Routing\\Pipeline->handleException(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#7 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /var/www/voten/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#9 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /var/www/voten/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#12 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#13 /var/www/voten/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#14 {main}
"} 
[2017-09-10 21:29:54] production.ERROR: Type is not supported {"userId":1,"email":"admin@admin.com","exception":"[object] (InvalidArgumentException(code: 0): Type is not supported at /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:71)
[stacktrace]
#0 /var/www/voten/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\\Http\\JsonResponse->setData(Array)
#1 /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(27): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 500, Array)
#2 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(435): Illuminate\\Http\\JsonResponse->__construct(Array, 500, Array, 192)
#3 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(186): Illuminate\\Foundation\\Exceptions\\Handler->prepareJsonResponse(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#4 /var/www/voten/app/Exceptions/Handler.php(76): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#5 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(83): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#6 /var/www/voten/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(55): Illuminate\\Routing\\Pipeline->handleException(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#7 /var/www/voten/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#8 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#9 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#10 /var/www/voten/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#11 {main}
"} 
[2017-09-10 21:29:54] production.ERROR: Type is not supported {"userId":1,"email":"admin@admin.com","exception":"[object] (InvalidArgumentException(code: 0): Type is not supported at /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:71)
[stacktrace]
#0 /var/www/voten/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\\Http\\JsonResponse->setData(Array)
#1 /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(27): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 500, Array)
#2 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(435): Illuminate\\Http\\JsonResponse->__construct(Array, 500, Array, 192)
#3 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(186): Illuminate\\Foundation\\Exceptions\\Handler->prepareJsonResponse(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#4 /var/www/voten/app/Exceptions/Handler.php(76): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#5 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(326): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#6 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(120): Illuminate\\Foundation\\Http\\Kernel->renderException(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#7 /var/www/voten/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#8 {main}
"} 
[2017-09-10 21:29:55] production.ERROR: Uncaught InvalidArgumentException: Type is not supported in /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:71
Stack trace:
#0 /var/www/voten/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\Http\JsonResponse->setData(Array)
#1 /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(27): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array, 500, Array)
#2 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(435): Illuminate\Http\JsonResponse->__construct(Array, 500, Array, 192)
#3 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(186): Illuminate\Foundation\Exceptions\Handler->prepareJsonResponse(Object(Illuminate\Http\Request), Object(InvalidArgumentException))
#4 /var/www/voten/app/Exceptions/Handler.php(76): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(InvalidArgumentException))
#5 /var/www/voten/vendor/laravel/fr {"userId":1,"email":"admin@admin.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Uncaught InvalidArgumentException: Type is not supported in /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:71
Stack trace:
#0 /var/www/voten/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\\Http\\JsonResponse->setData(Array)
#1 /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(27): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct(Array, 500, Array)
#2 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(435): Illuminate\\Http\\JsonResponse->__construct(Array, 500, Array, 192)
#3 /var/www/voten/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(186): Illuminate\\Foundation\\Exceptions\\Handler->prepareJsonResponse(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#4 /var/www/voten/app/Exceptions/Handler.php(76): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#5 /var/www/voten/vendor/laravel/fr at /var/www/voten/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:71)
[stacktrace]
#0 {main}
"} `

Any idea? 

Thanks a lor fot your help

**Comment by bildirio** [comment]
Hi @sullyfischer , Do you think is this issue related to update from php 7.0 to 7.1 ? I was not able to find any solution yet...

Many thanks for your help.

**Comment by sullyfischer** [comment]
Are you using MariaDB?

**Comment by bildirio** [comment]
Nope, MySQL

**Comment by sullyfischer** [comment]
is it v5.7+?

**Comment by bildirio** [comment]
Yes @sullyfischer : mysql  Ver 14.14 Distrib 5.7.19, for Linux (x86_64)

**Comment by bildirio** [comment]
I hadn't this issue before the update PHP 7.1 so deleted everything and tried again and  restarted the machine still got the same issue.

**Comment by sullyfischer** [comment]
Seems very odd to me. I suggest ask for a solution in our Slack team:
https://join.slack.com/t/voten/shared_invite/MjMzMTQxMzM4MDM2LTE1MDM5OTQ0NjEtMWRiMDhiZTY2Yg

**Comment by MrFahey** [comment]
@bildirio an exception will be cropping up in the background, however the reason you are seeing that "Type" error is because there was a bug in the laravel exception handler, see https://github.com/laravel/framework/pull/21149

Update Laravel and then you should be able to see what is going wrong.
