### ISSUE TITLE
Avatar/Profile Picture upload

### ISSUE THREAD

**Issue by incognito026** [voten-co/voten#171]
Can't upload a profile picture or channel avatar.
The thumbnail is uploading to the temp map but not visible for crop.

**Comment by incognito026** [comment]
Fixed with imagemagick

**Comment by sullyfischer** [comment]
What fixed it?

**Comment by bildirio** [comment]
Hello can you please help how did you setup picture upload? Even I did all setup for S3 it won't work. Shall i do extra setup or it should work with the login information provided on filesystems.php ?

**Comment by sullyfischer** [comment]
@bildirio at the moment, Voten only supports the FTP driver. In case you insist on using S3,  you should edit `PhotoTools.php` trait.

**Comment by yoginth** [comment]
I have configured my **ftp** though the avatar is **not uploading!**

![screenshot from 2017-11-20 08-29-55](https://user-images.githubusercontent.com/10177861/33000271-0e558394-cdcd-11e7-9c80-d69881d3c283.png)

**Comment by sullyfischer** [comment]
Try the new release. It should work
