### ISSUE TITLE
Is app running at `https://midd.voten.co` open source?

### ISSUE THREAD

**Issue by Gwill** [voten-co/voten#195]
Is app running at `https://midd.voten.co open` source?

https://github.com/voten-co/voten/blob/master/app/Traits/Submit.php#L68

and

https://github.com/voten-co/voten/blob/master/app/Traits/Submit.php#L181

**Comment by sullyfischer** [comment]
No it's not. However, it's not really doing much. I can't even remember which Laravel version it's using. 

The reason I used the `midd` server was to conceal our main server's IP address to protect against DDoS attacks.

**Comment by Gwill** [comment]
We are planning to fork voten to do a website. If we use your service(https://midd.voten.co), increase your burden. We dont think it is a good idea. 😂

**Comment by sullyfischer** [comment]
In that case your should create your own `mid` server, because we are going to (or maybe have) limit the mid server to respond only to our main server. 

In case you are going to write your own, this is the library I used to fetch info from external links: 
https://github.com/oscarotero/Embed
