### ISSUE TITLE
Error in logout, user delete etc.... Algolia trouble

### ISSUE THREAD

**Issue by citizen9** [voten-co/voten#196]
Algolia installed, ID and KEY right in .env, but i get this

AlgoliaSearch \ AlgoliaException (400)
Not enough rights to add an object near line:1 column:113

        $answer = Json::decode($response, true);
        $context->releaseMHandle($curlHandle);
        curl_close($curlHandle);
 
        if (intval($http_status / 100) == 4) {
            throw new AlgoliaException(isset($answer['message']) ? $answer['message'] : $http_status.' error', $http_status);
        } elseif (intval($http_status / 100) != 2) {
            throw new \Exception($http_status.': '.$response, $http_status);
        }
-------------
error here 

            throw new AlgoliaException(isset($answer['message']) ? $answer['message'] : $http_status.' error', $http_status);

-------------

**Comment by bildirio** [comment]
Hi @citizen9 , there are two types of Secret codes. Try the other one. (admin)

**Comment by citizen9** [comment]
Thanks, it works.
