### ISSUE TITLE
Can't load any file

### ISSUE THREAD

**Issue by citizen9** [voten-co/voten#197]
Any user can't load any file (IMG, GIF) from "Submission"

**Comment by sullyfischer** [comment]
Please explain more (and better)

**Comment by citizen9** [comment]
/submit
Trying to load gif or img and nothing happend.

**Comment by citizen9** [comment]
This error log from GIF download
xhr.js:178 POST http://test.srv/submit 404 (Not Found)
dispatchXhrRequest @ xhr.js:178
xhrAdapter @ xhr.js:12
dispatchRequest @ dispatchRequest.js:52
Promise resolved (async)
request @ Axios.js:58
Axios.(anonymous function) @ Axios.js:78
wrap @ bind.js:9
submit @ Submit.vue:262
boundFn @ vue.common.js:126
(anonymous) @ vue.common.js:2229
vue.common.js:521 [Vue warn]: Error when rendering anonymous component at resources/assets/js/components/Submit.vue: 
warn @ vue.common.js:521
Vue._render @ vue.common.js:3103
(anonymous) @ vue.common.js:2464
get @ vue.common.js:1661
run @ vue.common.js:1730
flushSchedulerQueue @ vue.common.js:1544
(anonymous) @ vue.common.js:473
nextTickHandler @ vue.common.js:422
Promise resolved (async)
timerFunc @ vue.common.js:437
queueNextTick @ vue.common.js:478
queueWatcher @ vue.common.js:1594
update @ vue.common.js:1720
notify @ vue.common.js:580
reactiveSetter @ vue.common.js:810
proxySetter @ vue.common.js:2063
(anonymous) @ Submit.vue:280
Promise rejected (async)
submit @ Submit.vue:271
boundFn @ vue.common.js:126
(anonymous) @ vue.common.js:2229
vue.common.js:435 TypeError: Cannot read property 'title' of undefined
    at Proxy.render (Submit.vue?3caa:94)
    at VueComponent.Vue._render (vue.common.js:3096)
    at VueComponent.<anonymous> (vue.common.js:2464)
    at Watcher.get (vue.common.js:1661)
    at Watcher.run (vue.common.js:1730)
    at flushSchedulerQueue (vue.common.js:1544)
    at Array.<anonymous> (vue.common.js:473)
    at nextTickHandler (vue.common.js:422)
    at <anonymous>
logError @ vue.common.js:435
Promise rejected (async)
timerFunc @ vue.common.js:437
queueNextTick @ vue.common.js:478
queueWatcher @ vue.common.js:1594
update @ vue.common.js:1720
notify @ vue.common.js:580
reactiveSetter @ vue.common.js:810
proxySetter @ vue.common.js:2063
(anonymous) @ Submit.vue:280
Promise rejected (async)
submit @ Submit.vue:271
boundFn @ vue.common.js:126
(anonymous) @ vue.common.js:2229
-----------
IMG
dropzone.js:1386 POST http://82.146.42.182/upload-photo 500 (Internal Server Error)
webpackJsonp../resources/assets/js/libs/dropzone.js.Dropzone.submitRequest @ dropzone.js:1386
webpackJsonp../resources/assets/js/libs/dropzone.js.Dropzone.uploadFiles @ dropzone.js:1382
webpackJsonp../resources/assets/js/libs/dropzone.js.Dropzone.processFiles @ dropzone.js:1176
webpackJsonp../resources/assets/js/libs/dropzone.js.Dropzone.processFile @ dropzone.js:1162
webpackJsonp../resources/assets/js/libs/dropzone.js.Dropzone.processQueue @ dropzone.js:1155
(anonymous) @ dropzone.js:1019
setTimeout (async)
webpackJsonp../resources/assets/js/libs/dropzone.js.Dropzone.enqueueFile @ dropzone.js:1017
(anonymous) @ dropzone.js:996
accept @ dropzone.js:154
webpackJsonp../resources/assets/js/libs/dropzone.js.Dropzone.accept @ dropzone.js:974
webpackJsonp../resources/assets/js/libs/dropzone.js.Dropzone.addFile @ dropzone.js:988
(anonymous) @ dropzone.js:573

**Comment by citizen9** [comment]
<a href='https://hostingkartinok.com/show-image.php?id=635aa3088168a5fb3137183f8a75c7b7' title='бесплатный хостинг картинок'><img src='https://s8.hostingkartinok.com/uploads/thumbs/2017/10/635aa3088168a5fb3137183f8a75c7b7.png' alt='Yes' /></a>
