### ISSUE TITLE
Translation help

### ISSUE THREAD

**Issue by citizen9** [voten-co/voten#199]
Sry what i open this question again, but nothing happend when i change category names and other words.
To translate category names, hot, new, rising....
I found in CategoryHeader.vue this
--------------------------------------
	<nav class="nav has-shadow user-select">
	    <div class="container">
	        <div class="nav-left">
	        	<router-link :to="{ path: '/c/' + $route.params.name }" class="nav-item is-tab" :class="{ 'is-active': sort == 'hot' }">
			=>>>>		Горячее \ HOT
				</router-link>

				<router-link :to="{ path: '/c/' + $route.params.name + '?sort=new' }" class="nav-item is-tab" :class="{ 'is-active': sort == 'new' }">
			=>>>>		Новое \ NEW
				</router-link>

				<router-link :to="{ path: '/c/' + $route.params.name + '?sort=rising'  }" class="nav-item is-tab" :class="{ 'is-active': sort == 'rising' }">
			=>>>>		Обсуждаемое \ RISING
				</router-link>
	        </div>
---------------------------------------
So i change, save it and nothing happend. It stays like before...

**Comment by sullyfischer** [comment]
You need to compile your js files after each change. Look up "Laravel Mix".
