### ISSUE TITLE
After rebuild 

### ISSUE THREAD

**Issue by citizen9** [voten-co/voten#201]
npm run watch 

and i got this 

ErrorException (E_ERROR)
Undefined index: /css/app.css (View: /var/www/stegmat/data/www/test.fvds.ru/resources/views/layouts/guest.blade.php) (View: /var/www/stegmat/data/www/test.fvds.ru/resources/views/layouts/guest.blade.php)

        $manifest = $manifests[$manifestPath];
 
        if (! isset($manifest[$path])) {
            report(new Exception("Unable to locate Mix file: {$path}."));
 
            if (! app('config')->get('app.debug')) {
                return $path;
            }
        }
 
        return new HtmlString($manifestDirectory.$manifest[$path]);
    }
}

**Comment by sullyfischer** [comment]
Try doing `npm run dev` before doing `npm run watch`

**Comment by citizen9** [comment]
Thanks it works
