### ISSUE TITLE
validation.uploaded

### ISSUE THREAD

**Issue by citizen9** [voten-co/voten#202]
When trying to load files from localhost/submit (GIF or IMG)
<a href='https://hostingkartinok.com/show-image.php?id=167f89a5f0b066bc488ec4e2c0aba107' title='поделиться фото'><img src='https://s8.hostingkartinok.com/uploads/thumbs/2017/10/167f89a5f0b066bc488ec4e2c0aba107.png' alt='Yes' /></a>
<a href='https://hostingkartinok.com/show-image.php?id=e407c162820c13e47cfbda7a7dab00de' title='загрузить фото'><img src='https://s8.hostingkartinok.com/uploads/thumbs/2017/10/e407c162820c13e47cfbda7a7dab00de.png' alt='Yes' /></a>

**Comment by peanut24** [comment]
Have you checked your log file for any errors?

**Comment by peanut24** [comment]
This seems to be the same as #197

**Comment by citizen9** [comment]
log file ./storage/logs ?

**Comment by citizen9** [comment]
#0 /var/www/html/vendor/algolia/algoliasearch-client-php/src/AlgoliaSearch/Client.php(808): AlgoliaSearch\\Client->doRequest(Object(AlgoliaSearch\\ClientContext), 'POST', 'TEST-dsn....', '/1/indexes/help...', Array, Array, 1, 5)
#1 /var/www/html/vendor/algolia/algoliasearch-client-php/src/AlgoliaSearch/Index.php(541): AlgoliaSearch\\Client->request(Object(AlgoliaSearch\\ClientContext), 'POST', '/1/indexes/help...', Array, Array, Array, 1, 5)
#2 /var/www/html/vendor/laravel/scout/src/Engines/AlgoliaEngine.php(121): AlgoliaSearch\\Index->search('dfgdfg', Array)
#3 /var/www/html/vendor/laravel/scout/src/Engines/AlgoliaEngine.php(78): Laravel\\Scout\\Engines\\AlgoliaEngine->performSearch(Object(Laravel\\Scout\\Builder), Array)
#4 /var/www/html/vendor/laravel/scout/src/Engines/Engine.php(89): Laravel\\Scout\\Engines\\AlgoliaEngine->search(Object(Laravel\\Scout\\Builder))
#5 /var/www/html/vendor/laravel/scout/src/Builder.php(172): Laravel\\Scout\\Engines\\Engine->get(Object(Laravel\\Scout\\Builder))
#6 /var/www/html/app/Http/Controllers/HelpController.php(32): Laravel\\Scout\\Builder->get()
#7 [internal function]: App\\Http\\Controllers\\HelpController->index(Object(Illuminate\\Http\\Request))
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\HelpController), 'index')
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(162): Illuminate\\Routing\\Route->runController()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(610): Illuminate\\Routing\\Route->run()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(571): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(549): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/html/app/Http/Middleware/Firewall.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\Firewall->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#32 /var/www/html/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#33 {main}
"}

**Comment by citizen9** [comment]
#0 /var/www/html/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_put_conten$
#1 [internal function]: Raven_Breadcrumbs_ErrorHandler->handleError(2, 'file_put_conten...', '/var/www/html/v...', 122, Array)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/var/www/html/s...', 'a:3:{s:9:\"_prev...', 2)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(83): Illuminate\\Filesystem\\Filesystem->put('/var/www/html/s...', 'a:3:{s:9:\$
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Store.php(128): Illuminate\\Session\\FileSessionHandler->write('EwiiZIjABsycO0U...', 'a:3:{s:9:\"_pre$
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(87): Illuminate\\Session\\Store->save()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(218): Illuminate\\Session\\Middleware\\StartSession->terminate(Object(Illuminate\\$
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(189): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\$
#8 /var/www/html/public/index.php(57): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#9 {main}
"}

**Comment by citizen9** [comment]
Fixed
