### ISSUE TITLE
installation full of errors.. can you help ?

### ISSUE THREAD

**Issue by akhilvarma** [voten-co/voten#205]

**Comment by peanut24** [comment]
Can you provide more information?

**Comment by akhilvarma** [comment]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'voten.suggesteds' doesn't exist (SQL: select `id`, `category_id` from `suggesteds` group by `category_id`)

D:\www\htdocs\voten\vendor\laravel\framework\src\Illuminate\Database\Connection.php


 catch (Exception $e) {
            throw new QueryException(
                $query, $this->prepareBindings($bindings), $e

**Comment by akhilvarma** [comment]
or if i give the server credentials ... can you install it for me plz...
