### ISSUE TITLE
guest.blade install stage

### ISSUE THREAD

**Issue by illuminate3** [voten-co/voten#206]
Error:

```
Parse error: syntax error, unexpected ')', expecting ']' (View:voten/resources/views/layouts/guest.blade.php)
```

the code

```
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(), 'env' => config('app.env'), 'pusherKey' => config('broadcasting.connections.pusher.key')) ?>
    </script>
```

I tried to revert to json_encode but then the page was locked up.

note: a goat told me about your site and then I found out it was laravel so had to try it out.

EDIT:

The token and env variables are causing the issue. If I take them out of the array I can see the page but then can't login with the default admin/password.

**Comment by illuminate3** [comment]
update: I upgrade brew and started a fresh install on a different machine. I got to the site. I had to refresh after entering the admin/password but I got in.

I went to change some settings and now I see this:
```
chmod(/Users/asus/Sites/voten/storage/oauth-public.key): Operation failed: Operation not permitted
```

storage is already 777.


Also, what services do I need to sign up for to make all this work properly?

I got pusher, sentry, redis.

Do I need echo and oauth?

**Comment by akhilvarma** [comment]
remove that script it works

**Comment by illuminate3** [comment]
I haven't tried doing that yet. I will give that a try.

**Comment by sullyfischer** [comment]
Have you tried running `npm run dev`?

**Comment by yoginth** [comment]
still it is not working for me!

**Comment by yoginth** [comment]
![screenshot from 2017-11-29 08-51-36](https://user-images.githubusercontent.com/10177861/33356639-90df06d8-d4e3-11e7-9307-d030266dec43.png)

**Comment by yoginth** [comment]
Please help to fix the issue! Support Open Source!

**Comment by peanut24** [comment]
Your array doesn't have a closing tag

**Comment by rethinkpattern** [comment]
Any fix for this, please I need to fix this.

**Comment by sullyfischer** [comment]
fixed
