### ISSUE TITLE
backend layout helper issue

### ISSUE THREAD

**Issue by akhilvarma** [voten-co/voten#209]
Undefined index: /js/backend.js (View: /var/www/html/community/fan/resources/views/layouts/backend-layout.blade.php) (View: /var/www/html/community/fan/resources/views/layouts/backend-layout.blade.php)

        return new HtmlString($manifestDirectory.$manifest[$path]);

**Comment by akhilvarma** [comment]
return new HtmlString($manifestDirectory.$manifest[$path]);

**Comment by sullyfischer** [comment]
run `npm run dev` in the console in order to compile (and create backend.js).
