### ISSUE TITLE
npm run production

### ISSUE THREAD

**Issue by citizen9** [voten-co/voten#210]
After make some changes in many .vue i do npm run production
and i got this

69% building modules 683/684 modules 1 active ...w/html/resources/assets/sass/app.scss[..................] | : info lifecy

so my changes applied not all...
i try npm run dev then npm run prod, same situation

and Voten stuck in dev mode 
"You are running Vue in development mode.
Make sure to turn on production mode when deploying for production."

**Comment by sullyfischer** [comment]
There's probably a syntax error somewhere in your code. After the compile fails, terminal prints the line that's failing. See which line is it. 

Also, to prevent this in the future, leave the `npm run watch` on so after each save, you'll be sure your code works; or see the error and fix it right away.

**Comment by citizen9** [comment]
Thanks, problem solved.
