### ISSUE TITLE
Can't change photo for channel

### ISSUE THREAD

**Issue by citizen9** [voten-co/voten#211]
Trying to change photo on channel.
<a href='https://hostingkartinok.com/show-image.php?id=183ac1c0894fdcbf2782046b5027a697' title='загрузить картинку'><img src='https://s8.hostingkartinok.com/uploads/thumbs/2017/11/183ac1c0894fdcbf2782046b5027a697.png' alt='Yes' /></a>

http://localhost/c/channel/mod/settings

**Comment by sullyfischer** [comment]
Please leave the exact error response you get (you're in the console tab of chrome. open network instead; and track the ajax request)

**Comment by citizen9** [comment]
exception:"Symfony\Component\Debug\Exception\FatalErrorException"
file:"/var/www/html/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php"
line:71
message:"Uncaught InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded in /var/www/html/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:71↵Stack trace:↵#0 /var/www/html/vendor/symfony/http-foundation/JsonResponse.php(50): Illuminate\Http\JsonResponse->setData(Array)↵#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(27): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array, 500, Array)↵#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(435): Illuminate\Http\JsonResponse->__construct(Array, 500, Array, 192)↵#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(186): Illuminate\Foundation\Exceptions\Handler->prepareJsonResponse(Object(Illuminate\Http\Request), Object(InvalidArgumentException))↵#4 /var/www/html/app/Exceptions/Handler.php(76): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(InvalidArgumentException))↵#5 /va"

**Comment by sullyfischer** [comment]
This again isn't the exact response I asked for. 
> you're in the console tab of chrome. open network instead; and track the ajax request
 
Do you have your working FTP setup ready?

**Comment by citizen9** [comment]
Yes vsftpd.
CDN must be sure?

**Comment by sullyfischer** [comment]
what?! Please write better English.

**Comment by yoginth** [comment]
He is using vsftpd.
