### ISSUE TITLE
npm run production (errors)

### ISSUE THREAD

**Issue by yoginth** [voten-co/voten#214]
Can't Install Voten on my Ubuntu System

Node: **v8.1.2**
NPM: **5.0.3**
OS: **Ubuntu Server 16.04.2 LTS**

While Running `npm run production` or `npm run dev` or `npm run watch` it displays the following errors!

![screenshot from 2017-11-19 18-00-18](https://user-images.githubusercontent.com/10177861/32990675-9a45c5a0-cd53-11e7-8c95-f618b4f1bc42.png)

**Comment by yoginth** [comment]
Fixed!

**Comment by sullyfischer** [comment]
It would be nice to leave the working solution.

**Comment by yoginth** [comment]
Just Updated Node (v9.2.0) and NPM (5.0.3) Versions.
