### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by Yoginth** [voten-co/voten#215]
I Installed Voten in my Local System (https://localhost:8000), but the Images are delivered through https://cdn.voten.co instead of https://localhost:8000, I have changed everything in .env, filesystem.php and wherever I see changed the URL to localhost:8000 still the files are delivering through voten's CDN so please help me with fixing this issue.

**Comment by sullyfischer** [comment]
Have you filled these values in the `.env`?
```
FTP_HOST=0.0.0.0
FTP_USERNAME=
FTP_PASSWORD=
CDN_URL=https://cdn.voten.co/
FTP_ROOT=/
```

**Comment by yoginth** [comment]
Yeah
