### ISSUE TITLE
Why Pusher and Socket?

### ISSUE THREAD

**Issue by Chinese1904** [voten-co/voten#22]
I see you use Pusher for local environments and socket.io for production environments. What's the reasoning behind this?

Why not use either for both?

**Comment by sullyfischer** [comment]
We use this on production server:
https://github.com/tlaverdure/laravel-echo-server

Sadly, the installation is not a breeze, but getting started with Pusher is super easy.

**Comment by Chinese1904** [comment]
I agree, I would use the same. Just wondering, thanks for explaining!
