### ISSUE TITLE
Got “Blocked:mixed content” on HTTPS website

### ISSUE THREAD

**Issue by yoginth** [voten-co/voten#220]
**What is the current behavior?**

I'm Running Voten in Production.

I was surprised to see in Chrome console the following error about loading the js file which is mixed with weback and laravel-mix

[Image](https://user-images.githubusercontent.com/10177861/33589080-7e7180da-d99c-11e7-88b8-d00094e0780b.png)

**My questions:**

- How can we have a mixed content on a website loaded using HTTPS protocol?
- How can I fix the error? I don't plan to serve website over HTTP and I want my js to load properly both in development and production.

**Comment by sullyfischer** [comment]
https://voten.co/c/voten/got-blockedmixed-content-on-https-website?comment=6008
