### ISSUE TITLE
Appointed Users in backend

### ISSUE THREAD

**Issue by citizen9** [voten-co/voten#223]
Trying to click "Appointed Users" in backend

<a href='https://hostingkartinok.com/show-image.php?id=450a5c134339badf6717399504a4fa01' title='photohost'><img src='https://s8.hostingkartinok.com/uploads/thumbs/2017/12/450a5c134339badf6717399504a4fa01.png' alt='Yes' /></a>

---LOG---
production.ERROR: Command "optimaze" is not defined.

Did you mean this?
    optimize {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"optimaze\" is not defined.

Did you mean this?
    optimize at /var/www/html/vendor/symfony/console/Application.php:609)
[stacktrace]

**Comment by sullyfischer** [comment]
Try these two:
`chmod 777 -R bootstrap/cache`
`chmod -R 777 storage/`

**Comment by citizen9** [comment]
Thats helps, but i got this

<a href='https://hostingkartinok.com/show-image.php?id=901c4ca1341d3618ef94ea3aca687098' title='photohost'><img src='https://s8.hostingkartinok.com/uploads/thumbs/2017/12/901c4ca1341d3618ef94ea3aca687098.png' alt='Yes' /></a>

**Comment by sullyfischer** [comment]
Have you ran the database seed? If you have, try clearing the Redis cache. 

> [2017-12-23 17:06:26] production.ERROR: Key file "file:///var/www/html/storage/oauth-public.key" permissions are not correct, should be 600 or 660 instea$
Have you followed the initial commands mentioned on the repository page? 

P.S: please use a better method for uploading screenshots! I

**Comment by citizen9** [comment]
Problem with chmod solved, but clearing Redis cache not help.
