### ISSUE TITLE
Can't sign in or up

### ISSUE THREAD

**Issue by rethinkpattern** [voten-co/voten#224]
How do i fix this. After installation the signin/singup button not working and the page even properly displayed

**Comment by sullyfischer** [comment]
try running `npm run dev`

**Comment by rethinkpattern** [comment]
tried and got this error Undefined index: /css/app.css

**Comment by sullyfischer** [comment]
can you leave me a screenshot or something?

**Comment by rethinkpattern** [comment]
![screenshot_20180102-080747](https://user-images.githubusercontent.com/26201409/34476793-3f2e6740-ef94-11e7-9a64-5b303cab5b44.png)

**Comment by rethinkpattern** [comment]
npm run production ends at 91%

**Comment by yoginth** [comment]
use node version 9.2.0

**Comment by sullyfischer** [comment]
Please try it with latest release (second beta)
