### ISSUE TITLE
Errors Updating, Creating Anything!

### ISSUE THREAD

**Issue by NoorQureshi** [voten-co/voten#227]
Keeps getting error! https://i.imgur.com/IdiWPIM.png

Can't update anything or create anything!

**Comment by sullyfischer** [comment]
Set your search settings (Algolia) in your `.env` file.

**Comment by NoorQureshi** [comment]
Worked! There's another issue with avatar uploading! Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Console**:
```
/upload-temp-avatar Failed to load resource: the server responded with a status of 500 (Internal Server Error)
vendor.js:1 Uncaught (in promise) Error: Request failed with status code 500
    at FtD3.e.exports (http://share.hacktoday.net/js/vendor.js?id=4fe080b0d82794dc7b26:1:278907)
    at e.exports (http://share.hacktoday.net/js/vendor.js?id=4fe080b0d82794dc7b26:1:47200)
    at XMLHttpRequest.f.(anonymous function) (http://share.hacktoday.net/js/vendor.js?id=4fe080b0d82794dc7b26:1:79726)
```

**Comment by NoorQureshi** [comment]
And only subscribed users to channel can see posts why? It should be public!

**Comment by sullyfischer** [comment]
Everyone can see posts, but to see it in your feed you must either subscribe to channels or simply change your feed settings. Wait my next release on Monday, it's more clear and easier to use.

**Comment by sullyfischer** [comment]
As for the error, have you entered proper values for FTP in your .env?

**Comment by NoorQureshi** [comment]
yes everything is perfect! this is what im getting while uploading profile or pictures... https://pastebin.com/70D3wQBJ

ftp is working fine!

**Comment by sullyfischer** [comment]
> ftp is working fine!
May I ask, how do you figure?

**Comment by NoorQureshi** [comment]
because i connected with filezilla and it worked! 

```
FTP_HOST=127.0.0.1
FTP_USERNAME=codepier
FTP_PASSWORD=
CDN_URL=http://hacktoday.io/
FTP_ROOT=/hacktoday.io/current/

```

**Comment by sullyfischer** [comment]
in case your hosting your web server at `http://hacktoday.io/`, the `CDN_URL` must be something different. 

Also, since the values of `.env` file are getting cached, make sure to run these commands after modifying them:

```
php artisan cache:clear
service php7.1-fpm restart
service nginx restart
php artisan config:cache
```

**Comment by NoorQureshi** [comment]
Now getting this: 
The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.

**Comment by sullyfischer** [comment]
I haven't seen this error myself but I'm guessing it's Laravel related. Google it man.
