### ISSUE TITLE
Parse error: syntax error, unexpected

### ISSUE THREAD

**Issue by NoorQureshi** [voten-co/voten#233]
Getting this error on hacktoday.io after deploying everything correctly.. and filling .env 
```
Parse error: syntax error, unexpected ')', expecting ']' (View: /home/codepier/hacktoday.io/20180130224233/resources/views/layouts/guest.blade.php) (View: /home/codepier/hacktoday.io/20180130224233/resources/views/layouts/guest.blade.php)

**Comment by NoorQureshi** [comment]
(1/1) RuntimeException
No application encryption key has been specified.

**Comment by sullyfischer** [comment]
Fixed by https://github.com/voten-co/voten/pull/234. Thanks for the report
