### ISSUE TITLE
npm run dev 69%

### ISSUE THREAD

**Issue by citizen9** [voten-co/voten#243]
Clean installation, in log this error

The Mix manifest does not exist. 
(View: /test/resources/views/layouts/guest.blade.php) 

> @ watch /var/www/user/data/www/test
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress -> -hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
>
> 10% building modules 3/3 modules 0 active                                         
>Webpack is watching the files…
>
>69% building modules 806/807 modules 1 active

**Comment by BoKKeR** [comment]
The issue is usually caused by having too little ram, enabling swap can help in the short run
