### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by citizen9** [voten-co/voten#244]
/storage/oauth-public.key" permissions are not correct, should be 600 or 660 instead of 644"

Change it to 600, 660 and 644
and got this
There is no existing directory at "/storage/logs" and its not buildable: Permission denied

**Comment by sullyfischer** [comment]
These commands usually does it for me:
```
`chmod 777 -R bootstrap/cache`
`chmod -R 777 storage/`
`chmod -R o+w laravel_blog/storage`
`chmod -R o+w storage`
`sudo chmod 755 -R you_laravel_project_name
```
