### ISSUE TITLE
Admin user

### ISSUE THREAD

**Issue by laravelish** [voten-co/voten#25]
Hello how do i create a admin user ?

i have created a admin user with role administrator but i get this error

HttpException in Application.php line 900:

**Comment by sullyfischer** [comment]
You mean a Voten-administrator right? Seems like I need to add a database seeder to make it easy for new installs. But anyways, create a record in `appointed_users` with your `user_id` and input `administrator` for `appointed_as`. Then clear redis cache so the app will now know you as administrator. 

This is only needed for the first user. After this you'd be able to open the admin panel `/backend` and add new administrators there.

**Comment by owwwe** [comment]
Hi @sullyfischer  got Whoops, looks like something went wrong. error on /backend. can't create as admin. Can you please give more information? Thank you.

**Comment by sullyfischer** [comment]
Hi. 
Did make the record(manually) into the database? And then did your clear Redis cahce?

**Comment by mustafabozkurt** [comment]
Does anyone know the default admin users or how to create a new one? I can't not access to backend. Thank you very much in advance.

**Comment by sullyfischer** [comment]
@mustafabozkurt there's a PR that would add it.

https://github.com/voten-co/voten/pull/24

**Comment by SunnyPage** [comment]
Please help ... I can not access the backend.
I called php artisan db:seed --class=AdminUserSeeder.
Removed all the bases of Redis.
