### ISSUE TITLE
Can't See my posts on HomePage

### ISSUE THREAD

**Issue by YoginthS** [voten-co/voten#303]
I Can't see my own posts on HomePage!

**Comment by sullyfischer** [comment]
I'm gonna need more than that

**Comment by YoginthS** [comment]
When i post something on voten i cant see my post which are upvoted!

**Comment by sullyfischer** [comment]
I'll fix it ASAP

**Comment by YoginthS** [comment]
fine waiting for the fix!

**Comment by sullyfischer** [comment]
fixed

**Comment by YoginthS** [comment]
Thanks

**Comment by sullyfischer** [comment]
You're welcome
