### ISSUE TITLE
Illuminate\Database\QueryExceptionApp\Http\Controllers\SubmissionController@store

### ISSUE THREAD

**Issue by YoginthS** [voten-co/voten#308]
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-5' for key 'PRIMARY' (SQL: insert into `submission_upvotes` (`created_at`, `ip_address`, `submission_id`, `updated_at`, `user_id`) values (2018-02-27 11:09:53, 157.50.253.159, 5, 2018-02-27 11:09:53, 2))
```

![screenshot](https://user-images.githubusercontent.com/36839013/36772990-7fd43426-1c7d-11e8-8234-427f8095ea37.png)

**Comment by YoginthS** [comment]
Still not fixed 🤔

**Comment by YoginthS** [comment]
this method is found in `api.php` but not in controller

**Comment by sullyfischer** [comment]
For the love of god, double check before you open issues. My time is very limited. The method does not exist in `api.php`. 

https://github.com/voten-co/voten/blob/master/routes/api.php

**Comment by YoginthS** [comment]
`SubmissionController@store` 

![screenshot](https://user-images.githubusercontent.com/36839013/36986855-ef075598-20c0-11e8-8180-de3a9fc6b8b3.png)

**Comment by sullyfischer** [comment]
I thought we were talking about #311

**Comment by YoginthS** [comment]
have a patch?

**Comment by sullyfischer** [comment]
For #311 I do. This one I can't reproduce; I need more details

**Comment by YoginthS** [comment]
when I upvoted multiple times I got this in **Sentry**

**Comment by sullyfischer** [comment]
Will work on it

**Comment by YoginthS** [comment]
Thanks for consideration

**Comment by sullyfischer** [comment]
Thanks for reporting it
