### ISSUE TITLE
Method App\Http\Controllers\BanController::store does not exist.

### ISSUE THREAD

**Issue by YoginthS** [voten-co/voten#311]
Can't ban user!

![screenshot](https://user-images.githubusercontent.com/36839013/36853159-b4d73472-1d93-11e8-937b-4eb70f29182e.png)

**Comment by sullyfischer** [comment]
You're not running the latest version.

**Comment by YoginthS** [comment]
I'm running the latest version of voten @ votepen.tk

**Comment by sullyfischer** [comment]
In latest version there is no `BanController@store` anymore in the `api.php`.

**Comment by YoginthS** [comment]
but it is in `web.php`

**Comment by YoginthS** [comment]
did you find that @sullyfischer ?

**Comment by YoginthS** [comment]
This one exists in `routes/web.php`

![screenshot](https://user-images.githubusercontent.com/36839013/36987131-a660e90c-20c1-11e8-9d05-dd1af1cf21c2.png)

**Comment by sullyfischer** [comment]
resolved. Don't mind the lack of redirection after the form is submitted. I'm to migrate it into the SPA panel.

**Comment by YoginthS** [comment]
but still destroy is not working!
