### ISSUE TITLE
Feature Request: Gravatar Implementation

### ISSUE THREAD

**Issue by YoginthS** [voten-co/voten#315]
Desired Feature: It is better to have the **Gravatar** implementation in VotePen to make the profile more attractive at the beginning like **GitHub** does!

**Comment by sullyfischer** [comment]
it's *Voten.

**Comment by YoginthS** [comment]
Sorry, Fixed Typo! What is the reason for not implementing!

**Comment by sullyfischer** [comment]
I intend to make "avatar update" easier in the future. Maybe add some pre choices; maybe generate avatars from their username, etc.
