### ISSUE TITLE
Upload Profile Photo - Stuck Constantly

### ISSUE THREAD

**Issue by owwwe** [voten-co/voten#32]
Hi Voten!,
Quick question, when I'M trying to upload a profile picture it's shows constantly "Please position and size your photo" but nothing happen just stuck constantly. Anyone can help me what could be the reason? Thanks in advance.

owwwe!

**Comment by sullyfischer** [comment]
Hi there

Have you set the values for the CDN server (FTP) in the .env file?

**Comment by mustafabozkurt** [comment]
Hi @sullyfischer  is there any other way to connect it? I'am unable to connect it via AWS S3 bucket.

**Comment by sullyfischer** [comment]
Hi @mustafabozkurt, I haven't tried S3 before, but I'm guessing it should work just fine. Take a look at `config/filesystems.php` and change the driver to s3 and then enter your values. Please let me know how it goes.

**Comment by mustafabozkurt** [comment]
Hi @sullyfischer I have edited the filesystems.php file with my S3(aws s3 full access) details and still no results. Searched almost all the web for it and so far I haven't been able to find any solution..  it just says 'Please position and size your photo'  hopefully will someone find the solution and share it over here don't wanna miss this awesome app. Thank you

**Comment by sullyfischer** [comment]
@mustafabozkurt could you send me your AWS info so I can test it myself?

**Comment by mustafabozkurt** [comment]
HI @sullyfischer just sent it via E-mail

**Comment by sullyfischer** [comment]
@mustafabozkurt just got your email. I will look into it as notify you the results. Thanks for the trust

**Comment by sullyfischer** [comment]
@bildirio I got it working by:
installing S3 Driver:
```
composer require league/flysystem-aws-s3-v3
```

and then there was another exception saying:
```
fstat() expects parameter 1 to be resource, object given
```

Whereever that's thrown you need to make this kind of change the affected line. For example in `PhotoTools.php`, change:
```Storage::put($folder.'/'.$filename, $image);```
to:
```
Storage::put($folder.'/'.$filename, $image->__toString());
```

**Comment by sullyfischer** [comment]
I closed the issue but feel free to continue

**Comment by sullyfischer** [comment]
@bildirio you mean it's still not working? 
If not, please comment those `try` codes to see the thrown exceptions so we can track em further.

**Comment by yoginth** [comment]
I Want to use it locally still I'm stuck!
