### ISSUE TITLE
unexpected 'protected' (T_PROTECTED)

### ISSUE THREAD

**Issue by YoginthS** [voten-co/voten#320]
**protected** function linkSubmission(Request $request)

**Comment by YoginthS** [comment]
Please tell the reason and close it! This is the culture of Open Source! THANKS!

**Comment by sullyfischer** [comment]
I give no reason when the issue itself isn't giving details.

**Comment by YoginthS** [comment]
no, I'm posting this for notifying that issue is there! if I won't notify it will take too long to fix this issue!

**Comment by sullyfischer** [comment]
What issue? Where? Please provide details.

**Comment by YoginthS** [comment]
in `app/Traits/Submit.php` when I click suggest button after pasting the link, it displaying exception like `Oops Something went wrong`
