### ISSUE TITLE
Move to Travis CI

### ISSUE THREAD

**Issue by YoginthS** [voten-co/voten#321]
Circle CI has a limit of 1500 minutes, cuz voten takes too long to build on circle ci (2 - 3 Mins Per build), so it is better to move to Travis, it is used by millions of developers and it is scalable for any application so I request voten to move to Travis, Thank You, Much Love!

**Comment by sullyfischer** [comment]
I believe 1500 mins is more than enough for Voten. Instead of spending time learning about a new service, I rather spend time on optimizing this one (using caches)
