### ISSUE TITLE
Logout is too slow on 2G Networks

### ISSUE THREAD

**Issue by YoginthS** [voten-co/voten#323]
**Algoila** is running when the user is logging out so it takes too long and time, sometimes it fails to log out in 2G network connections.

**Comment by sullyfischer** [comment]
How do you know Algolia is running?

**Comment by YoginthS** [comment]
Sometimes getting algolia error

**Comment by YoginthS** [comment]
Fixed by changing `SCOUT_DRIVER` to `null`
