### ISSUE TITLE
i have installed on digital occean but getting error

### ISSUE THREAD

**Issue by amirgee007** [voten-co/voten#337]
root@xabaar:/var/www/voten-laravel# php artisan cache:clear

   Predis\Connection\ConnectionException  : Connection refused [tcp://127.0.0.1:6379]

  at /var/www/voten-laravel/vendor/predis/predis/src/Connection/AbstractConnection.php:155
    151|      */
    152|     protected function onConnectionError($message, $code = null)
    153|     {
    154|         CommunicationException::handle(
  > 155|             new ConnectionException($this, static::createExceptionMessage($message), $code)
    156|         );
    157|     }
    158|
    159|     /**

  Exception trace:

  1   Predis\Connection\AbstractConnection::onConnectionError("Connection refused")
      /var/www/voten-laravel/vendor/predis/predis/src/Connection/StreamConnection.php:128

  2   Predis\Connection\StreamConnection::createStreamSocket(Object(Predis\Connection\Parameters), "tcp://127.0.0.1:6379")
      /var/www/voten-laravel/vendor/predis/predis/src/Connection/StreamConnection.php:178

  Please use the argument -v to see more details.

**Comment by amirgee007** [comment]
Connection refused [tcp://127.0.0.1:6379] {"exception":"[object] (Predis\\Connection\\ConnectionException(code: 111): Connection refused [tcp://127.0.0.1:6379] at /var/www/voten-laravel/vendor/predis/predis/src/Connection/AbstractConnection.php:155)
--

**Comment by amirgee007** [comment]
we must need to set it up on nignix i am using mysql apache right now?

**Comment by sullyfischer** [comment]
Something's wrong with your Redis setup. Google it with "laravel" keyword. It's not Voten related.
