### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by mikk-io** [voten-co/voten#342]
It's still a bit unclear how you would deploy the web application using CodePier, I tried that, and there are alot of cors issues and whatsoever.

**Comment by sullyfischer** [comment]
@lukepolo might be the one helping you with that.

**Comment by lukepolo** [comment]
Those should be cleared up, let me know if there are still some issues.

**Comment by sullyfischer** [comment]
@lukepolo you just broke the record of the fastest reply in the history of Github 👍
