### ISSUE TITLE
401 Unauthorized Errors

### ISSUE THREAD

**Issue by trchristensen** [voten-co/voten#344]
The site is set up on my local machine. I'm using Valet. Followed the installation commands and configured the .env. Can you help me figure this out? Thanks.

<img width="414" alt="screen shot 2018-09-15 at 5 49 20 am" src="https://user-images.githubusercontent.com/6512813/45578392-6e0c0500-b8ab-11e8-9d71-af8bd7e96f3b.png">

**Comment by trchristensen** [comment]
I got it working by not using Valet. Thanks.

**Comment by trchristensen** [comment]
I was wrong. Still getting the same issues. Sorry for closing and reopening.

**Comment by sullyfischer** [comment]
Have you followed the instructions for Laravel Passport as well?

**Comment by trchristensen** [comment]
php artisan passport:install ? Of course. Is there something I'm missing? Am I required to authenticate with the voten.co public API to get this working?

**Comment by LEVATHIAN** [comment]
> Have you followed the instructions for Laravel Passport as well?

I'm having the same issue and i have not found any Passport instructions you are talking about, please link them?

Thank you.

**Comment by sullyfischer** [comment]
@LEVATHIAN 
```
php artisan key:generate
php artisan migrate
php artisan passport:install
```

**Comment by LEVATHIAN** [comment]
> ```
> php artisan passport:install
> ```

Still getting the same issue

**Comment by amiller911** [comment]
> > ```
> > php artisan passport:install
> > ```
> 
> Still getting the same issue

**sullyfischer** dont help fix problem.

**Comment by sullyfischer** [comment]
@amiller911 what?!

**Comment by sullyfischer** [comment]
@LEVATHIAN please look it up as a "Laravel Passport" issue on the net

**Comment by LEVATHIAN** [comment]
> @LEVATHIAN please look it up as a "Laravel Passport" issue on the net

I have been trying to fix the problem for 2 weeks with no resulsts, i looked up all possible solutions.

**Comment by Fyris** [comment]
Having the same issue, did try all the commands listed above and in the installation instructions.

**Comment by metellius** [comment]
Looks like this is the issue: https://github.com/laravel/passport/issues/795
TokenGuard.php in passport expects jwt token to be serialized, but laravel has serialize set to false by default, so there's an exception thrown from unserialize.

**Comment by BoKKeR** [comment]
Somehow I still can't figure out how to fix this. Any hints?

**Comment by LEVATHIAN** [comment]
> Somehow I still can't figure out how to fix this. Any hints?

Upgrade to Passport 7.0 and Laravel 5.7.x.

**Comment by tott** [comment]
> ```
> "laravel/framework": "5.7.*",
> "laravel/passport": "^7.0",
> "pbmedia/laravel-ffmpeg": "^3.0.0",
> "php-ffmpeg/php-ffmpeg": "dev-master#c11b79ab5b0174aa1a56c54c67491169e78a4c17",
> ```

This worked perfectly for me! Thanks @BoKKeR
