### ISSUE TITLE
Messages.vue and Notifications.vue (error)

### ISSUE THREAD

**Issue by amiller911** [voten-co/voten#348]
Hello.

Why dont working Messages and Notifications? 
In console i get it 2 error.

![bag](https://user-images.githubusercontent.com/42842521/48112606-c3500b80-e289-11e8-8b19-7ed636288536.png)

**Comment by BoKKeR** [comment]
You need to use either pusher, or echo. Did you define a service? https://github.com/voten-co/voten/blob/master/.env.example#L33-L42
