### ISSUE TITLE
Block Recommended

### ISSUE THREAD

**Issue by amiller911** [voten-co/voten#351]
How get block "Recommended"?
![2018-12-01 14 45 12](https://user-images.githubusercontent.com/42842521/49325614-36425e80-f578-11e8-8a70-1742b717624d.png)

**Comment by sullyfischer** [comment]
You need to mark channels as recommended from the admin. Don't forget to clear cache.

**Comment by amiller911** [comment]
> You need to mark channels as recommended from the admin. Don't forget to clear cache.
Where exactly does this need to be turned on? In your channel settings not found. In the admin area, too, nothing. Thanks.
