### ISSUE TITLE
Notification have error (Pusher)

### ISSUE THREAD

**Issue by amiller911** [voten-co/voten#363]
Hello.

I try setup notification, but its not working.

My .ENV
`PUSHER_APP_ID=710700
PUSHER_APP_KEY=80bc3bfb9332cdbc975b
PUSHER_APP_SECRET=7bf92108ea73534e5b83
PUSHER_CLUSTER=ap1`

My broadcasting.php
`'pusher' => [
          'driver' => 'pusher',
          'key' => env('PUSHER_APP_KEY'),
          'secret' => env('PUSHER_APP_SECRET'),
          'app_id' => env('PUSHER_APP_ID'),
          'options' => [
              'cluster' => 'ap1',
              'encrypted' => false,
          ],
      ],`

My bootstarp.js
`import Echo from 'laravel-echo';
window.Echo = new Echo({
broadcaster: 'pusher',
key: '80bc3bfb9332cdbc975b',
cluster: 'ap1',
encrypted: false
});`

In console i get error from stats.pucher.com:
`Failed to load resource: the server responded with a status of 500 (Request Blocked)`

How to fix problem? Thank you.

**Comment by BoKKeR** [comment]
Do you have adblock on by any chance?

**Comment by amiller911** [comment]
> Do you have adblock on by any chance?

No i dont have adblock.

Have any idea?

**Comment by amiller911** [comment]
Notification about the message of personal work.
Notification of new replies does not work.
Constant status in notifications 0.
![2019-02-11 2 47 11](https://user-images.githubusercontent.com/42842521/52538651-c89c8500-2da7-11e9-8527-ba1e4971ae89.png)
How to gix its problem?
