### ISSUE TITLE
Data output from MYSQL to template

### ISSUE THREAD

**Issue by amiller911** [voten-co/voten#368]
Could you tell me please as to withdraw from MYSQL data in pattern? (view.php)

You need to display the name of the channel. How can I do that?

**Comment by sullyfischer** [comment]
I don't understand the question. Please explain better.

**Comment by amiller911** [comment]
> I don't understand the question. Please explain better.

I don't want to use Vue.

Me need a template to display the title of the article and the link of the article (In the database is the 

> Submission - Title

 and 

> Submission - Slug

How to display the name in the template (submission.view)? I try 

> {{  $submission->title }}

 in view template, but i get error 

> ErrorException (E_ERROR) Undefined variable: submission

Thank you.
