### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by tangod0wn** [voten-co/voten#37]
Love voten!

Just wondering, 
The channels are being sucesfully created and are saved & visible for me only as long as the user is signed in. 

No channels are displayed for non logged in users or are searchable.

It doesn't seem to be based on Auth permissions and was just wondering, how can I change this?

**Comment by sullyfischer** [comment]
Hi, I'm glad you liked it. 

Could you send me an example URL that doesn't work for non-logged-in users? (cuz it should have worked!)

**Comment by tangod0wn** [comment]
You've done an awesome job with it! Ty again for making this open source. 
Once I've created a channel, It's not visible on the homepage that the channel exists.

At first I wasn't sure if it was because I haven't added Elastic Search keys, but inside of the CategoryController@show method, it seems as if the newly created channels should be appearing on the homepage.

<img width="1406" alt="screen shot 2017-06-25 at 8 51 55 pm" src="https://user-images.githubusercontent.com/12672363/27515519-4955ea78-59e8-11e7-8c3e-e485652c207a.png">

**Comment by sullyfischer** [comment]
Thanks! Means a lot to hear that. Honestly, I've used tons of open-source packages in it, would have been unfair not to make it open-source!

You don't HAVE TO use Elastic on **local**. The mysql driver works just fine. 
In this case though, the guest-sidebar displays only channels that have been added to the suggested-channels list (by administrator). I should also mention that the search in the sidebar is client-side and made using Vue code.

**Comment by sullyfischer** [comment]
I'm closing this, but feel free to continue.

**Comment by tangod0wn** [comment]
No worries! :) yes I definitely agree, without github & stackoverflow coding everything from scratch can become sooo time consuming.

Ohh ok thank you, to add channels into the suggested-chanel list as administrator, is that done by just creating a new channel from the Admin user made from the AdminUserSeeder? Or is there something else I'm missing.

**Comment by sullyfischer** [comment]
It doesn't matter who creates the channel. Login by Administrator user (the first one is created by AdminUserSeeder, the rest can be added from `/backend/appointed-users`) and then navigate to `/big-daddy/suggested-categories` and the rest is obvious.

**Comment by tangod0wn** [comment]
Oh ok, thank you for your help!

I might be missing something though just``big-daddy/suggested-categories`` returns a 404 / can't see it anywhere in the route file. ``suggested-categories`` obviously just returns null,

**Comment by sullyfischer** [comment]
You shouldn't get a 404. It's defined in `routes.js` file.

**Comment by tangod0wn** [comment]
Sorry it was completely my fault, I forgot to clear the redis cache & then it worked perfectly.
