### ISSUE TITLE
Website is OFF!

### ISSUE THREAD

**Issue by BaseMax** [voten-co/voten#370]
Hello,
I'm Max.

http://voten.co/
Error 525 Ray ID: 507f0964eef94326
SSL handshake failed

![Capture](https://user-images.githubusercontent.com/2658040/63217893-775cbc00-c163-11e9-8c00-aaf86f3dfb3f.PNG)

Regards.
Max Base

**Comment by sullyfischer** [comment]
Hello Max. please read #369
