### ISSUE TITLE
translation for persian farsi language

### ISSUE THREAD

**Issue by wikiccu** [voten-co/voten#375]
Hi
is it ok if I send a new language and translation files for this project?

**Comment by saleh-mir** [comment]
Hi
Send it how?

**Comment by wikiccu** [comment]
I meant a PR for translation files in resources.

**Comment by saleh-mir** [comment]
Voten isn't really multi language. You'd have to fork it and translate it for yourself

**Comment by wikiccu** [comment]
thank you
