### ISSUE TITLE
Question about why category_name

### ISSUE THREAD

**Issue by rodrigobutta** [voten-co/voten#54]
Hi!! First of all, congratulations for this project, i think Laravel needs projects like this in order to rule in what frontend too.

I was looking at your code in order to understand how it works (i'm new in Vue) and i've noticed you are using a category_name in the sumissions model, when you've just could be joining submissions with categories with the category_id that it{s present in te model too by making a 

`protected $with = ['owner','category'];`

in the Sumission model

and then accessing it data by submission.category.name instead of submission.category_name

Is there a reason about this redundant field? Performance may be?

I hope i've been clear about my point/question because my english is not too good!!

Bye!

**Comment by sullyfischer** [comment]
Hi! Thank you so much. 

Yes, Performance exactly. Take your home feed for example, let's say there are 20 submissions, using relations to fetch the category_name it'll take the mySQL 20 more queries while having a `cateogry_name` column in `submissions` table would do the trick. 

Sure it's not the best practice way to accomplish this (probably using redis for home-feed as well would be the best practice method), but at the moment it saves of queries and doesn't harm us really.

**Comment by rodrigobutta** [comment]
Hi! Thank you very much, now i now we are in syntony about that. I share your thought about that redundant field that will save planty of queries while the cache instance is under construction. Have a nice day and i will follow near your awesome work.

**Comment by sullyfischer** [comment]
@rodrigobutta glad I could help. Would love you to step by the community itself.
