### ISSUE TITLE
Feature Request: RTL language support

### ISSUE THREAD

**Issue by hqubaisi** [voten-co/voten#68]
Hi @sullyfischer,

can you please add support for RTL languages (Arabic, Hebrew, etc), I really appreciate you effort.

& thanks in advance

**Comment by sullyfischer** [comment]
Hi @hqubaisi. 

I'm afraid that's not going to happen in a close future. Are you trying to run an alternative platform in a RTL language?

**Comment by hqubaisi** [comment]
no, the exact same platform but with RTL support
