### ISSUE TITLE
Chat not auto update

### ISSUE THREAD

**Issue by folkevil** [voten-co/voten#69]
I tried with latest version, pusher configs are correct but i tested real-time chat, it look like not auto update messages. Need to refresh page to see notification (and browser not store state when in chat screen too)

**Comment by sullyfischer** [comment]
are you running queue? (`php artisan queue:work`)

**Comment by folkevil** [comment]
Ah, it worked, i forgot about queue.

**Comment by yoginth** [comment]
then how it is used for production?

**Comment by sullyfischer** [comment]
@yoginth googling helps:
https://laravel.com/docs/5.5/queues#supervisor-configuration
