### ISSUE TITLE
Migration API from kliqqi.com to voten

### ISSUE THREAD

**Issue by palpalani** [voten-co/voten#92]
I like to use voten app for my existing pligg.com(New name kliqq.com) based site. Is there any migration API available?

**Comment by sullyfischer** [comment]
I didn't get what your app (pligg.com) actually is and how it can be used with Voten. Could you please explain more what you're trying to accomplish? Thanks

**Comment by palpalani** [comment]
Kliqqi is also similar application, demo available here: http://demos5.softaculous.com/Kliqqi/new.php
But it is not up to date with latest PHP version. I found Voten is a similar application, so I want to migrate existing site to Voten.

If Voten has import API then I will use that for migration.

**Comment by sullyfischer** [comment]
I see. What do you mean by "import API" though? Do you mean like an api to get the posts and comments?

**Comment by palpalani** [comment]
Yes, I want to link create API.

**Comment by sullyfischer** [comment]
A **public API** is in my ToDo list but it's not done yet.

**Comment by YoginthS** [comment]
Now its WIP
