### ISSUE TITLE
Error in some mobile broswer

### ISSUE THREAD

**Issue by toneywu** [voten-co/voten#96]
After Login there is nothing except top navbar.
such as 
UC Browser (Android)

**Comment by sullyfischer** [comment]
Could you please a screenshot?

**Comment by toneywu** [comment]
sorry i cannot upload on github, please check the following URL

http://www.handalm.com/1stpage.jpg
the 1st one is the correct index page.

http://www.handalm.com/2ndPage.png
the 2nd one is the incorrect page after login.

I have tried a lot of mobile browsers, almost all looks like the same, only a few can pass the test.
Please do try it on a typical browser like UC Browser (Android)...

**Comment by sullyfischer** [comment]
Does it get work after a refresh?

**Comment by toneywu** [comment]
no, it dosen't

**Comment by toneywu** [comment]
@sullyfischer not only my hosted app, but also voten.co has this issue.

**Comment by mikeydiamonds** [comment]
I am having this same issue. It seems the same as closed issue  #132. My screenshot would look exactly the same.

**Comment by sullyfischer** [comment]
@mikeydiamonds it's not the same as #132. #132 is solved now. This one however seems to be with UC browsers or any other browser which doesn't support ES5 JavaScript syntax. In case that's causing this, I think we should lead affected users to download mobile apps instead (which we'll begin developing soon)

**Comment by mikeydiamonds** [comment]
You were correct, I had a slightly older version with the bug in it. Thanks for making this well polished software open source. I'm learning a great deal. If I find any way to contribute I certainly will do so.
