### ISSUE TITLE
Post not shown in Subscribed channel, which is created by the owner

### ISSUE THREAD

**Issue by toneywu** [voten-co/voten#97]
1. Create a Channel.
2. Subscribe / Unsubscribe, there is another bug: you can still subscribe channel created by yourself, and there are 2 duplicated channels listed in the left Navbar
3. Submit a post.
4. back to home and the post is not shown in u subscribed channel, but it listed in all channels

**Comment by sullyfischer** [comment]
I tested this on my machine and a few others, could reproduce the issue.
